### PR TITLE
replaced parslet with simple_po_parser to speedup parsing by up to 500x

### PR DESCRIPTION
**Pull request by dfherr**
I rewrote the whole parser using the low-level strscan library as it took over 30seconds to parse one of our bigger po files. This rewrite increases performance of parsing by up to 500 times.

benchmark_fastparser_vs_parslet

You can find the simple_po_parser here: https://github.com/experteer/simple_po_parser

I also fixed some stuff. 
* coveralls falsely only covered the spec files
* obsolete is now the default name instead of cached. 
* Two alias method bugs were fixed.
* Header didn't have the inspect overwrite, so I added it for spec purposes and consistency

This pull requests contains the whole development history, not every commit is relevant to the final version.

As you might notice I use a personalized version in our geminabox-server, but I still think it would be great that the main project addes this changes.

### CODE REVIEW

**Comment by arashm** [comment]
This looks like a huge work! Thank you. I have to take a close look to realize what's going on there.

**Comment by dfherr** [comment]
@arashm just look at the new project and the difference after the last commit. Going through the commits is definitely not worth it. 

My first attempt was to improve the parslet parser, but after I didn't get further than ~5% speed improvement I started to rewrite it with strscanner. Finally I split the projects and extracted the parser into it's own repository. This project is basically now a "frontend" which objectifies the parser hash output from the new project.

You would also see a lot of benchmark, debug and compare tasks in the Rakefile that I removed for the final merge.

**Comment by arashm** [comment]
@dfherr I knew that the GEM is really slow but any attempt to speed it up was really not noticeable as Parslet was the major bottleneck. My idea was to rewrite the parser in another language like Rust, but the plan had one problem which was that I didn't know Rust 😄

**Comment by dfherr** [comment]
I can totally relate :) I initially wanted to rewrite it in C and compile it as an ruby extension. I actually did some work in C and C++, but as [StringScanner](https://ruby-doc.org/stdlib-2.2.0/libdoc/strscan/rdoc/StringScanner.html) is basically an adapter to a C scanner I thought it's not worth the extra trouble. And I would say it's fast enough now. The benchmark you see in the start posting are 100 runs on the 200 message / ~680 lines test/benchmark.po file. Meaning the parser needs ~3ms for it one run compared to ~1.44 seconds.

The new implementation is even about twice as fast as https://github.com/grosser/get_pomo I used before (and there I had to parse the comments into smaller pieces after the first parse which was not included in the benchmark)

**Comment by dfherr** [comment]
added a fix that joins comments occuring multiple times with a space instead of nothing.

This is espacially important for reference comments, where references can be on the same line seperated by space or on multiple lines.

```
#: reference1 reference2

#: reference1
#: reference2
```

**Comment by dfherr** [comment]
after thinking again, joining them with newline seems like the better solution, as they actually are on different lines.

**Comment by dfherr** [comment]
just wanna let you know, that I had no issues so far using the PoParser with the simple_po_parser core.

**Comment by arashm** [comment]
@dfherr Ah, sorry. Totally forgot about this. Busy these days. Will release a new version soon.

**Comment by dfherr** [comment]
@arashm thanks for merging. If you like you can also give me contributor rights to this project and rubygems (https://rubygems.org/profiles/dfherr), and I will help maintaining the gem.

Looks like we will also link from https://github.com/grosser/get_pomo to this project now.

**Pull request merged**
